import contextlib
import io
import tempfile
import tomllib
from pathlib import Path

import cvxpy as cp
import pytest

from cvxgenrust import cgr
from cvxgenrust.generator import (
    CLARABEL_VERSION,
    GENERATED_PYTHON_DEPENDENCIES,
    GENERATED_REQUIRES_PYTHON,
    _python_package_name,
    _snake_case,
    extract_problem,
)

from tests.support import GeneratedCodeTestCase


@pytest.mark.metadata
class MetadataTests(GeneratedCodeTestCase):
    def test_generated_name_normalization(self):
        self.assertEqual(_snake_case(""), "cgr_solver")
        self.assertEqual(_snake_case("class"), "class_solver")
        self.assertEqual(_snake_case("Trace SDP"), "trace_sdp")
        self.assertEqual(_python_package_name("123 solver"), "cgr_123_solver")

    def test_extract_problem_metadata(self):
        spec = extract_problem(self._build_nonneg_ls_problem().problem, module_name="nonneg_ls")
        self.assertEqual(spec.module_name, "nonneg_ls")
        self.assertEqual(spec.parameter_vec_len, 10)
        self.assertEqual([parameter.name for parameter in spec.parameters], ["A", "b"])
        self.assertEqual(spec.parameters[0].size, 6)
        self.assertEqual([variable.name for variable in spec.variables], ["x"])

    def test_generate_code_writes_crate(self):
        problem = self._build_nonneg_ls_problem().problem
        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir) / "nonneg_ls_cgr"
            package_version = tomllib.loads(
                (Path(__file__).resolve().parent.parent / "pyproject.toml").read_text(encoding="utf-8")
            )["project"]["version"]
            progress = io.StringIO()
            with contextlib.redirect_stderr(progress):
                project = cgr.generate_code(problem, code_dir=output_dir, module_name="nonneg_ls", wrapper=False)
            progress_text = progress.getvalue()
            self.assertIn("[CvxGenRust] Extracting problem data", progress_text)
            self.assertIn("[CvxGenRust] Writing Rust crate and Python package files", progress_text)
            self.assertIn("[CvxGenRust] Done. Generated solver project", progress_text)
            cargo_toml = output_dir / "Cargo.toml"
            lib_rs = output_dir / "src" / "lib.rs"
            readme = output_dir / "README.html"
            package_dir = output_dir / "python" / "nonneg_ls_cgr"
            wrapper = package_dir / "cgr_solver.py"
            pyproject = output_dir / "pyproject.toml"
            package_init = package_dir / "__init__.py"
            rust_example = output_dir / "examples" / "solve.rs"
            self.assertTrue(cargo_toml.exists())
            self.assertTrue(lib_rs.exists())
            self.assertTrue(readme.exists())
            self.assertFalse((output_dir / "README.md").exists())
            self.assertTrue(wrapper.exists())
            self.assertTrue(pyproject.exists())
            self.assertTrue(package_init.exists())
            self.assertTrue(rust_example.exists())
            self.assertEqual(project.spec.module_name, "nonneg_ls")
            cargo_text = cargo_toml.read_text(encoding="utf-8")
            self.assertIn("pub struct CGRProblem", lib_rs.read_text(encoding="utf-8"))
            self.assertIn("def cgr_solve", wrapper.read_text(encoding="utf-8"))
            self.assertIn("pyo3", cargo_text)
            self.assertIn('version = "0.1.0"', cargo_text)
            self.assertIn(f'clarabel = "{CLARABEL_VERSION}"', cargo_text)
            self.assertNotIn('features = ["sdp-accelerate"]', cargo_text)
            self.assertNotIn('features = ["sdp-openblas"]', cargo_text)
            self.assertIn('crate-type = ["rlib", "cdylib"]', cargo_text)
            pyproject_text = pyproject.read_text(encoding="utf-8")
            self.assertIn('name = "nonneg-ls-cgr"', pyproject_text)
            self.assertIn('version = "0.1.0"', pyproject_text)
            self.assertIn(f'requires-python = "{GENERATED_REQUIRES_PYTHON}"', pyproject_text)
            self.assertIn('module-name = "nonneg_ls_cgr.nonneg_ls"', pyproject_text)
            self.assertIn('python-source = "python"', pyproject_text)
            for dependency in GENERATED_PYTHON_DEPENDENCIES:
                self.assertIn(f'"{dependency}"', pyproject_text)
            self.assertNotIn("from .cgr_solver", package_init.read_text(encoding="utf-8"))
            self.assertIn("pub fn solve(&self)", lib_rs.read_text(encoding="utf-8"))
            self.assertIn(f"Generated by CvxGenRust v{package_version}", lib_rs.read_text(encoding="utf-8"))
            self.assertIn("Generated at:", lib_rs.read_text(encoding="utf-8"))
            self.assertIn("cvxgenrust_solve", lib_rs.read_text(encoding="utf-8"))
            readme_text = readme.read_text(encoding="utf-8")
            self.assertIn('problem.register_solve("CGR", cgr_solve)', readme_text)
            self.assertIn("from nonneg_ls_cgr.cgr_solver import cgr_solve", readme_text)
            self.assertIn("nonneg_ls_cgr/python", readme_text)
            self.assertIn("PYTHONPATH", readme_text)
            self.assertIn('method="CGR"', readme_text)
            self.assertIn("updated_params", readme_text)
            self.assertIn("cargo run --example solve", readme_text)
            self.assertNotIn("examples/solve.py", readme_text)

    @pytest.mark.sdp
    def test_generate_code_enables_sdp_backend_for_psd_cones(self):
        problem = self._build_sdp_problem().problem
        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir) / "trace_sdp_cgr"
            cgr.generate_code(problem, code_dir=output_dir, module_name="trace_sdp", wrapper=False)
            cargo_text = (output_dir / "Cargo.toml").read_text(encoding="utf-8")

            self.assertIn('features = ["sdp-accelerate"]', cargo_text)
            self.assertIn('features = ["sdp-openblas"]', cargo_text)

    def test_extract_socp_problem_metadata(self):
        x = cp.Variable(3, name="x")
        A = cp.Parameter((4, 3), name="A")
        b = cp.Parameter(4, name="b")
        rho = cp.Parameter(nonneg=True, name="rho")
        problem = cp.Problem(
            cp.Minimize(cp.sum_squares(A @ x - b) + 0.1 * cp.sum_squares(x)),
            [cp.norm(x, 2) <= rho, x >= 0, cp.sum(x) <= 1],
        )

        spec = extract_problem(problem, module_name="regularized_socp")
        self.assertEqual(spec.module_name, "regularized_socp")
        self.assertEqual(spec.cone_dims.soc, [4])

    def test_extract_parametric_quad_form_metadata(self):
        spec = extract_problem(
            self._build_parametric_quad_form_problem().problem,
            module_name="param_qp",
        )

        self.assertEqual(spec.module_name, "param_qp")
        self.assertEqual(
            [(parameter.name, parameter.size) for parameter in spec.parameters],
            [("P", 3), ("q", 2)],
        )
        self.assertEqual(spec.parameters[0].pack, "upper_tri")
        self.assertGreater(len(spec.p_map.reduced.data), 0)

    @pytest.mark.sdp
    def test_extract_sdp_problem_metadata(self):
        spec = extract_problem(self._build_sdp_problem().problem, module_name="trace_sdp")

        self.assertEqual(spec.module_name, "trace_sdp")
        self.assertEqual(spec.cone_dims.psd, [2])
