import tempfile
import tomllib
from pathlib import Path

import cvxpy as cp

from cvxgenrust import cgr
from cvxgenrust.generator import extract_problem

from tests.support import GeneratedCodeTestCase


class MetadataTests(GeneratedCodeTestCase):
    def test_extract_problem_metadata(self):
        spec = extract_problem(self._build_nonneg_ls_problem().problem, module_name="nonneg_ls")
        self.assertEqual(spec.module_name, "nonneg_ls")
        self.assertEqual(spec.parameter_vec_len, 10)
        self.assertEqual([parameter.name for parameter in spec.parameters], ["A", "b"])
        self.assertEqual(spec.parameters[0].size, 6)
        self.assertEqual([variable.name for variable in spec.variables], ["x"])

    def test_generate_code_writes_crate(self):
        problem = self._build_nonneg_ls_problem().problem
        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir) / "nonneg_ls_cgr"
            package_version = tomllib.loads(
                (Path(__file__).resolve().parent.parent / "pyproject.toml").read_text(encoding="utf-8")
            )["project"]["version"]
            project = cgr.generate_code(problem, code_dir=output_dir, module_name="nonneg_ls")
            cargo_toml = output_dir / "Cargo.toml"
            lib_rs = output_dir / "src" / "lib.rs"
            readme = output_dir / "README.md"
            wrapper = output_dir / "cgr_solver.py"
            rust_example = output_dir / "examples" / "solve.rs"
            self.assertTrue(cargo_toml.exists())
            self.assertTrue(lib_rs.exists())
            self.assertTrue(readme.exists())
            self.assertTrue(wrapper.exists())
            self.assertTrue(rust_example.exists())
            self.assertEqual(project.spec.module_name, "nonneg_ls")
            self.assertIn("pub struct CGRProblem", lib_rs.read_text(encoding="utf-8"))
            self.assertIn("class CGRProblem", wrapper.read_text(encoding="utf-8"))
            self.assertIn('clarabel = "0.11.1"', cargo_toml.read_text(encoding="utf-8"))
            self.assertIn('crate-type = ["rlib", "cdylib"]', cargo_toml.read_text(encoding="utf-8"))
            self.assertIn("pub fn solve(&self)", lib_rs.read_text(encoding="utf-8"))
            self.assertIn(f"Generated by CvxGenRust v{package_version}", lib_rs.read_text(encoding="utf-8"))
            self.assertIn("Generated at:", lib_rs.read_text(encoding="utf-8"))
            self.assertIn("cvxgenrust_solve", lib_rs.read_text(encoding="utf-8"))
            readme_text = readme.read_text(encoding="utf-8")
            self.assertIn('problem.register_solve("CGR", cgr_solve)', readme_text)
            self.assertIn("from nonneg_ls_cgr.cgr_solver import cgr_solve", readme_text)
            self.assertIn('method="CGR"', readme_text)
            self.assertIn("updated_params", readme_text)
            self.assertNotIn("examples/solve.py", readme_text)

    def test_extract_socp_problem_metadata(self):
        x = cp.Variable(3, name="x")
        A = cp.Parameter((4, 3), name="A")
        b = cp.Parameter(4, name="b")
        rho = cp.Parameter(nonneg=True, name="rho")
        problem = cp.Problem(
            cp.Minimize(cp.sum_squares(A @ x - b) + 0.1 * cp.sum_squares(x)),
            [cp.norm(x, 2) <= rho, x >= 0, cp.sum(x) <= 1],
        )

        spec = extract_problem(problem, module_name="regularized_socp")
        self.assertEqual(spec.module_name, "regularized_socp")
        self.assertEqual(spec.cone_dims.soc, [4])
