from __future__ import annotations
from datetime import datetime
import json
import keyword
import math
import re
import shutil
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import cvxpy as cp
import numpy as np
import scipy.sparse as sp

TEMPLATES_DIR = Path(__file__).with_name("templates")
PYPROJECT_PATH = Path(__file__).resolve().parent.parent / "pyproject.toml"
GENERATOR_DISPLAY_NAME = "CvxGenRust"


def _load_generator_version() -> str:
    project_data = tomllib.loads(PYPROJECT_PATH.read_text(encoding="utf-8"))
    return str(project_data["project"]["version"])


GENERATOR_VERSION = _load_generator_version()


@dataclass
class MatrixPatternSpec:
    rows: int
    cols: int
    indices: list[int]
    indptr: list[int]


@dataclass
class CsrMatrixSpec:
    rows: int
    cols: int
    indptr: list[int]
    indices: list[int]
    data: list[float]


@dataclass
class AffineCscMapSpec:
    reduced: CsrMatrixSpec
    pattern: MatrixPatternSpec


@dataclass
class AffineVectorMapSpec:
    reduced: CsrMatrixSpec
    output_len: int


@dataclass
class ParameterSpec:
    name: str
    shape: tuple[int, ...]
    size: int
    offset: int


@dataclass
class VariableSpec:
    name: str
    shape: tuple[int, ...]
    size: int
    offset: int


@dataclass
class ConeDimsSpec:
    zero: int
    nonneg: int
    exp: int
    soc: list[int]
    psd: list[int]
    p3d: list[float]


@dataclass
class ProblemSpec:
    module_name: str
    parameter_vec_len: int
    cone_dims: ConeDimsSpec
    parameters: list[ParameterSpec]
    variables: list[VariableSpec]
    p_map: AffineCscMapSpec
    a_map: AffineCscMapSpec
    q_map: AffineVectorMapSpec


@dataclass
class GeneratedRustProject:
    spec: ProblemSpec
    output_dir: Path


def _snake_case(name: str) -> str:
    candidate = re.sub(r"[^a-zA-Z0-9]+", "_", name).strip("_").lower() or "generated_problem"
    if keyword.iskeyword(candidate):
        candidate = f"{candidate}_problem"
    return candidate


def _load_template(name: str) -> str:
    return (TEMPLATES_DIR / name).read_text(encoding="utf-8")


def _fill_template(template: str, **values: str) -> str:
    for key, value in values.items():
        template = template.replace(f"__{key}__", value)
    return template


def _comment_block(prefix: str, lines: list[str]) -> str:
    return "\n".join(f"{prefix} {line}" if line else prefix.rstrip() for line in lines)


def _generated_header(prefix: str, artifact: str, generated_at: str, module_name: str | None = None) -> str:
    lines = [
        f"Generated by {GENERATOR_DISPLAY_NAME} v{GENERATOR_VERSION}",
        f"Generated at: {generated_at}",
        f"Artifact: {artifact}",
        "This file is auto-generated. Manual edits may be overwritten.",
    ]
    if module_name is not None:
        lines.insert(3, f"Problem module: {module_name}")
    return _comment_block(prefix, lines)


def _rust_ident(name: str) -> str:
    candidate = re.sub(r"[^a-zA-Z0-9]+", "_", name).strip("_").lower()
    if not candidate:
        candidate = "generated"
    if candidate[0].isdigit():
        candidate = f"p_{candidate}"
    if keyword.iskeyword(candidate):
        candidate = f"{candidate}_value"
    return candidate


def _rust_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _rust_usize_slice(values: list[int] | tuple[int, ...]) -> str:
    return "&[" + ", ".join(f"{value}usize" for value in values) + "]"


def _rust_usize_vec(values: list[int]) -> str:
    return "vec![" + ", ".join(f"{value}usize" for value in values) + "]"


def _rust_f64(value: float) -> str:
    if math.isnan(value):
        raise ValueError("NaN coefficients are not supported")
    if math.isinf(value):
        return "f64::INFINITY" if value > 0 else "f64::NEG_INFINITY"
    if value == 0.0:
        return "0.0"
    return repr(float(value))


def _rust_f64_vec(values: list[float]) -> str:
    return "vec![" + ", ".join(_rust_f64(value) for value in values) + "]"


def _csr_spec(matrix: sp.spmatrix | sp.sparray) -> CsrMatrixSpec:
    csr = sp.csr_array(matrix)
    return CsrMatrixSpec(
        rows=int(csr.shape[0]),
        cols=int(csr.shape[1]),
        indptr=[int(x) for x in csr.indptr.tolist()],
        indices=[int(x) for x in csr.indices.tolist()],
        data=[float(x) for x in csr.data.tolist()],
    )


def _pattern_spec(indices: Any, indptr: Any, shape: tuple[int, int]) -> MatrixPatternSpec:
    return MatrixPatternSpec(
        rows=int(shape[0]),
        cols=int(shape[1]),
        indices=[int(x) for x in np.asarray(indices).tolist()],
        indptr=[int(x) for x in np.asarray(indptr).tolist()],
    )


def _extract_map(reduced_mat_obj: Any) -> AffineCscMapSpec:
    reduced_mat_obj.cache(True)
    if reduced_mat_obj.problem_data_index is None or reduced_mat_obj.reduced_mat is None:
        raise ValueError("reduced matrix does not expose a problem-data sparsity pattern")
    indices, indptr, shape = reduced_mat_obj.problem_data_index
    return AffineCscMapSpec(
        reduced=_csr_spec(reduced_mat_obj.reduced_mat),
        pattern=_pattern_spec(indices, indptr, shape),
    )


def _extract_vector_map(q_map: sp.spmatrix | sp.sparray) -> AffineVectorMapSpec:
    csr = _csr_spec(q_map)
    return AffineVectorMapSpec(reduced=csr, output_len=csr.rows - 1)


def _extract_cone_dims(dims: Any) -> ConeDimsSpec:
    return ConeDimsSpec(
        zero=int(getattr(dims, "zero", 0)),
        nonneg=int(getattr(dims, "nonneg", 0)),
        exp=int(getattr(dims, "exp", 0)),
        soc=[int(x) for x in getattr(dims, "soc", [])],
        psd=[int(x) for x in getattr(dims, "psd", [])],
        p3d=[float(x) for x in getattr(dims, "p3d", [])],
    )


def _zero_csc_map_spec(rows: int, cols: int, parameter_vec_len: int) -> AffineCscMapSpec:
    return AffineCscMapSpec(
        reduced=CsrMatrixSpec(
            rows=0,
            cols=parameter_vec_len,
            indptr=[0],
            indices=[],
            data=[],
        ),
        pattern=MatrixPatternSpec(
            rows=rows,
            cols=cols,
            indices=[],
            indptr=[0] * (cols + 1),
        ),
    )


def extract_problem(
    problem: cp.Problem,
    module_name: str = "generated_problem",
) -> ProblemSpec:
    if not problem.is_dpp():
        raise ValueError("problem must satisfy CVXPY's DPP rules for code generation")
    cvxpy_solver = cp.CLARABEL
    data, _, _ = problem.get_problem_data(cvxpy_solver)
    param_prob = data["param_prob"]
    parameter_vec_len = int(param_prob.total_param_size + 1)
    canonical_dim = int(getattr(param_prob.x, "size", data["A"].shape[1]))
    if param_prob.reduced_P.problem_data_index is None or param_prob.reduced_P.reduced_mat is None:
        p_map = _zero_csc_map_spec(canonical_dim, canonical_dim, parameter_vec_len)
    else:
        p_map = _extract_map(param_prob.reduced_P)
    a_map = _extract_map(param_prob.reduced_A)
    linear_obj_tensor = getattr(param_prob, "q", None)
    if linear_obj_tensor is None:
        linear_obj_tensor = getattr(param_prob, "c")
    linear_obj_map = _extract_vector_map(linear_obj_tensor)
    dims = _extract_cone_dims(data["dims"])
    parameters = []
    for parameter in param_prob.parameters:
        name = parameter.name() or f"param_{parameter.id}"
        offset = int(param_prob.param_id_to_col[parameter.id])
        parameters.append(
            ParameterSpec(
                name=name,
                shape=tuple(int(x) for x in parameter.shape),
                size=int(parameter.size),
                offset=offset,
            )
        )

    variables = []
    for variable in problem.variables():
        if variable.id not in param_prob.var_id_to_col:
            continue
        name = variable.name() or f"var_{variable.id}"
        offset = int(param_prob.var_id_to_col[variable.id])
        variables.append(
            VariableSpec(
                name=name,
                shape=tuple(int(x) for x in variable.shape),
                size=int(variable.size),
                offset=offset,
            )
        )

    return ProblemSpec(
        module_name=_snake_case(module_name),
        parameter_vec_len=parameter_vec_len,
        cone_dims=dims,
        parameters=parameters,
        variables=variables,
        p_map=p_map,
        a_map=a_map,
        q_map=linear_obj_map,
    )


def _render_csr(name: str, spec: CsrMatrixSpec) -> str:
    return f"""let {name} = CsrMatrix {{
        rows: {spec.rows}usize,
        cols: {spec.cols}usize,
        indptr: {_rust_usize_vec(spec.indptr)},
        indices: {_rust_usize_vec(spec.indices)},
        data: {_rust_f64_vec(spec.data)},
    }};"""


def _render_pattern(name: str, spec: MatrixPatternSpec) -> str:
    return f"""let {name} = MatrixPattern {{
        rows: {spec.rows}usize,
        cols: {spec.cols}usize,
        indices: {_rust_usize_vec(spec.indices)},
        indptr: {_rust_usize_vec(spec.indptr)},
    }};"""


def _render_parameter_info(parameter: ParameterSpec) -> str:
    return f"""ParameterInfo {{
        name: {_rust_string(parameter.name)},
        shape: {_rust_usize_slice(parameter.shape)},
        size: {parameter.size}usize,
        offset: {parameter.offset}usize,
    }}"""


def _render_variable_info(variable: VariableSpec) -> str:
    return f"""VariableInfo {{
        name: {_rust_string(variable.name)},
        shape: {_rust_usize_slice(variable.shape)},
        size: {variable.size}usize,
        offset: {variable.offset}usize,
    }}"""


def _render_cone_dims(spec: ConeDimsSpec) -> str:
    return f"""ConeDims {{
            zero: {spec.zero}usize,
            nonneg: {spec.nonneg}usize,
            exp: {spec.exp}usize,
            soc: {_rust_usize_vec(spec.soc)},
            psd: {_rust_usize_vec(spec.psd)},
            p3d: {_rust_f64_vec(spec.p3d)},
        }}"""


def _render_generated_lib(spec: ProblemSpec, generated_at: str) -> str:
    parameters = ",\n    ".join(_render_parameter_info(parameter) for parameter in spec.parameters)
    variables = ",\n    ".join(_render_variable_info(variable) for variable in spec.variables)

    param_setters = []
    for parameter in spec.parameters:
        ident = _rust_ident(parameter.name)
        param_setters.append(
            f"""    pub fn set_{ident}(&mut self, value: &[f64]) -> Result<(), RuntimeError> {{
        self.set_parameter({_rust_string(parameter.name)}, value)
    }}
"""
        )

    variable_getters = []
    for variable in spec.variables:
        ident = _rust_ident(variable.name)
        variable_getters.append(
            f"""    pub fn extract_{ident}(&self, solution: &[f64]) -> Result<Vec<f64>, RuntimeError> {{
        self.extract_variable({_rust_string(variable.name)}, solution)
    }}
"""
        )

    cone_push_lines = []
    if spec.cone_dims.zero > 0:
        cone_push_lines.append(
            "        cones.push(SupportedConeT::<f64>::ZeroConeT(canonical.cones.zero));"
        )
    if spec.cone_dims.nonneg > 0:
        cone_push_lines.append(
            "        cones.push(SupportedConeT::<f64>::NonnegativeConeT(canonical.cones.nonneg));"
        )
    if spec.cone_dims.soc:
        cone_push_lines.append(
            "        for dim in &canonical.cones.soc {\n            cones.push(SupportedConeT::<f64>::SecondOrderConeT(*dim));\n        }"
        )
    if spec.cone_dims.psd:
        cone_push_lines.append(
            "        for dim in &canonical.cones.psd {\n            cones.push(SupportedConeT::<f64>::PSDTriangleConeT(*dim));\n        }"
        )
    if spec.cone_dims.exp > 0:
        cone_push_lines.append(
            "        for _ in 0..canonical.cones.exp {\n            cones.push(SupportedConeT::<f64>::ExponentialConeT());\n        }"
        )
    if spec.cone_dims.p3d:
        cone_push_lines.append(
            "        for alpha in &canonical.cones.p3d {\n            cones.push(SupportedConeT::<f64>::PowerConeT(*alpha));\n        }"
        )
    cone_push_code = "\n".join(cone_push_lines)
    canonical_method = _fill_template(
        _load_template("clarabel_canonical_method.rs.tmpl"),
        P_REDUCED=_render_csr("p_reduced", spec.p_map.reduced),
        P_PATTERN=_render_pattern("p_pattern", spec.p_map.pattern),
        A_REDUCED=_render_csr("a_reduced", spec.a_map.reduced),
        A_PATTERN=_render_pattern("a_pattern", spec.a_map.pattern),
        Q_REDUCED=_render_csr("c_reduced", spec.q_map.reduced),
        Q_OUTPUT_LEN=str(spec.q_map.output_len),
        CONE_DIMS=_render_cone_dims(spec.cone_dims),
    )
    solve_method = _fill_template(
        _load_template("clarabel_solve_method.rs.tmpl"),
        CONE_PUSH_CODE=cone_push_code,
    )
    ffi_methods = _fill_template(
        _load_template("clarabel_ffi.rs.tmpl"),
        PARAMETER_VEC_LEN=str(spec.parameter_vec_len),
        PARAMETER_VEC_LEN_MINUS_ONE=str(spec.parameter_vec_len - 1),
    )

    return _fill_template(
        _load_template("cgr_lib.rs.tmpl"),
        RUNTIME_RS=_fill_template(
            _load_template("runtime.rs"),
            HEADER=_generated_header(
                "//",
                "Rust runtime support",
                generated_at,
                module_name=spec.module_name,
            ),
        ),
        PARAMETER_COUNT=str(len(spec.parameters)),
        PARAMETERS=parameters,
        VARIABLE_COUNT=str(len(spec.variables)),
        VARIABLES=variables,
        PARAMETER_VEC_LEN_MINUS_ONE=str(spec.parameter_vec_len - 1),
        CANONICAL_METHOD=canonical_method,
        SOLVE_METHOD=solve_method,
        FFI_METHODS=ffi_methods,
        PARAM_SETTERS="".join(param_setters),
        VARIABLE_GETTERS="".join(variable_getters),
    )


def _render_generated_cargo(crate_name: str, generated_at: str) -> str:
    dependencies = 'clarabel = "0.11.1"'
    return _fill_template(
        _load_template("Cargo.toml.tmpl"),
        HEADER=_generated_header(
            "#",
            "Cargo manifest",
            generated_at,
            module_name=crate_name,
        ),
        CRATE_NAME=crate_name,
        LIB_NAME=crate_name.replace("-", "_"),
        DEPENDENCIES=dependencies,
    )


def _render_generated_readme(spec: ProblemSpec, generated_at: str) -> str:
    parameter_lines = "\n".join(
        f"- `{parameter.name}`: shape={parameter.shape}, size={parameter.size}, offset={parameter.offset}"
        for parameter in spec.parameters
    )
    variable_lines = "\n".join(
        f"- `{variable.name}`: shape={variable.shape}, size={variable.size}, offset={variable.offset}"
        for variable in spec.variables
    )
    setter_lines = "\n".join(
        f"problem.set_{_rust_ident(parameter.name)}(&vec![0.0; {parameter.size}])?;"
        for parameter in spec.parameters
    )
    value_lines = ""
    if spec.variables:
        variable = spec.variables[0]
        ident = _rust_ident(variable.name)
        value_lines = (
            f"\nlet {ident} = problem.extract_{ident}(&solution.x)?;\n"
            f'println!("value = {{:?}}", {ident});'
        )
    rust_usage = _fill_template(
        """```rust
use __MODULE_NAME__::CGRProblem;

let mut problem = CGRProblem::new();
__SETTER_LINES__

let solution = problem.solve()?;
println!("status = {}", solution.status);
println!("objective = {}", solution.obj_val);__VALUE_LINES__
```

Run the generated example executable with:

```bash
cargo run --example solve
```
""",
        MODULE_NAME=spec.module_name,
        SETTER_LINES=setter_lines,
        VALUE_LINES=value_lines,
    )
    python_usage = _fill_template(
        """```python
import numpy as np
import __PACKAGE_NAME__ as cgr
from __PROBLEM_MODULE__ import problem, __PARAMETER_NAMES____VARIABLE_IMPORT__

cgr.register_solve_method()
__PARAM_ASSIGNMENTS__

problem.solve(
    method="__SOLVER_METHOD_NAME__",
    updated_params=[__UPDATED_PARAMS__],
    warm_start=False,
)
print(problem.status)
```

The Python wrapper builds and loads the generated Rust shared library in-process via `ctypes`.
See `examples/solve.py` for the matching generated usage example.
""",
        PACKAGE_NAME=spec.module_name + "_cgr",
        PROBLEM_MODULE=spec.module_name,
        PARAMETER_NAMES=", ".join(parameter.name for parameter in spec.parameters),
        VARIABLE_IMPORT=(
            ", " + ", ".join(variable.name for variable in spec.variables)
            if spec.variables
            else ""
        ),
        PARAM_ASSIGNMENTS="\n".join(
            f"{parameter.name}.value = "
            + (
                "0.0"
                if parameter.size == 1
                else f"np.zeros({repr(tuple(parameter.shape)) if len(parameter.shape) != 1 else f'({parameter.shape[0]},)'})"
            )
            for parameter in spec.parameters
        ),
        SOLVER_METHOD_NAME=f"{spec.module_name}_cgr",
        UPDATED_PARAMS=", ".join(repr(parameter.name) for parameter in spec.parameters),
    )
    return _fill_template(
        _load_template("cgr_README.md.tmpl"),
        HEADER="> Generated by "
        + f"{GENERATOR_DISPLAY_NAME} v{GENERATOR_VERSION}"
        + f" on {generated_at}"
        + f" for module `{spec.module_name}`.\n"
        + "> This directory is auto-generated.",
        MODULE_NAME=spec.module_name,
        PARAMETER_LINES=parameter_lines,
        VARIABLE_LINES=variable_lines,
        RUST_USAGE=rust_usage,
        PYTHON_USAGE=python_usage,
    )


def _render_generated_init(spec: ProblemSpec, generated_at: str) -> str:
    return _fill_template(
        _load_template("cgr___init__.py"),
        HEADER=_generated_header(
            "#",
            "Python package re-export",
            generated_at,
            module_name=spec.module_name,
        ),
    )


def _render_generated_python_wrapper(spec: ProblemSpec, generated_at: str) -> str:
    parameter_entries = ",\n    ".join(
        json.dumps(
            {
                "name": parameter.name,
                "shape": list(parameter.shape),
                "size": parameter.size,
                "offset": parameter.offset,
            }
        )
        for parameter in spec.parameters
    )
    variable_entries = ",\n    ".join(
        json.dumps(
            {
                "name": variable.name,
                "shape": list(variable.shape),
                "size": variable.size,
                "offset": variable.offset,
            }
        )
        for variable in spec.variables
    )

    param_helpers = []
    for parameter in spec.parameters:
        ident = _rust_ident(parameter.name)
        param_helpers.append(
            f"""    def set_{ident}(self, value):
        self.set_parameter("{parameter.name}", value)
"""
        )

    return _fill_template(
        _load_template("cgr_solver.py.tmpl"),
        HEADER=_generated_header(
            "#",
            "Python wrapper metadata",
            generated_at,
            module_name=spec.module_name,
        ),
        PARAMETER_ENTRIES=parameter_entries,
        VARIABLE_ENTRIES=variable_entries,
        PARAMETER_VEC_LEN=str(spec.parameter_vec_len),
        PARAM_HELPERS="".join(param_helpers),
        LIB_NAME=spec.module_name.replace("-", "_"),
        SOLVER_METHOD_NAME=f"{spec.module_name}_cgr",
    )


def _render_generated_rust_example(spec: ProblemSpec, generated_at: str) -> str:
    param_setup = []
    for parameter in spec.parameters:
        ident = _rust_ident(parameter.name)
        param_setup.append(
            f"""    problem.set_{ident}(&vec![0.0; {parameter.size}])?;"""
        )

    variable_readback = ""
    if spec.variables:
        first_variable = spec.variables[0]
        first_ident = _rust_ident(first_variable.name)
        variable_readback = f"""
    let {first_ident} = problem.extract_{first_ident}(&solution.x)?;
    println!("{first_ident} = {{:?}}", {first_ident});"""

    solve_call = "problem.solve()?"

    return _fill_template(
        _load_template("cgr_solve.rs.tmpl"),
        HEADER=_generated_header(
            "//",
            "Rust example executable",
            generated_at,
            module_name=spec.module_name,
        ),
        MODULE_NAME=spec.module_name,
        PARAM_SETUP=chr(10).join(param_setup),
        SOLVE_CALL=solve_call,
        VARIABLE_READBACK=variable_readback,
    )


def _render_generated_python_example(spec: ProblemSpec, package_name: str, generated_at: str) -> str:
    import_names = ["problem", *[parameter.name for parameter in spec.parameters]]
    if spec.variables:
        import_names.extend(variable.name for variable in spec.variables)

    param_value_setup = []
    for parameter in spec.parameters:
        shape = list(parameter.shape)
        shape_literal = repr(tuple(shape)) if len(shape) != 1 else f"({shape[0]},)"
        value_expr = "0.0" if parameter.size == 1 else f"np.zeros({shape_literal})"
        param_value_setup.append(f"    {parameter.name}.value = {value_expr}")

    variable_prints = []
    for variable in spec.variables:
        variable_prints.append(
            f'    print("{variable.name} =", {variable.name}.value)'
        )

    return _fill_template(
        _load_template("cgr_solve.py.tmpl"),
        HEADER=_generated_header(
            "#",
            "Python CVXPY usage example",
            generated_at,
            module_name=spec.module_name,
        ),
        PACKAGE_NAME=package_name,
        PROBLEM_MODULE=spec.module_name,
        PROBLEM_IMPORTS=", ".join(import_names),
        PARAM_VALUE_SETUP="\n".join(param_value_setup),
        SOLVER_METHOD_NAME=f"{spec.module_name}_cgr",
        UPDATED_PARAMS=", ".join(repr(parameter.name) for parameter in spec.parameters),
        VARIABLE_PRINTS="\n".join(variable_prints),
    )


def generate_code(
    problem: cp.Problem,
    code_dir: str | Path = "generated_problem",
    module_name: str | None = None,
) -> GeneratedRustProject:
    output_dir = Path(code_dir)
    module = module_name or output_dir.name
    spec = extract_problem(problem, module_name=module)
    generated_at = datetime.now().astimezone().isoformat(timespec="seconds")

    src_dir = output_dir / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    (output_dir / "Cargo.toml").write_text(
        _render_generated_cargo(spec.module_name, generated_at), encoding="utf-8"
    )
    (src_dir / "lib.rs").write_text(_render_generated_lib(spec, generated_at), encoding="utf-8")
    (output_dir / "README.md").write_text(
        _render_generated_readme(spec, generated_at), encoding="utf-8"
    )
    (output_dir / "problem.json").unlink(missing_ok=True)
    (output_dir / "__init__.py").write_text(
        _render_generated_init(spec, generated_at), encoding="utf-8"
    )
    (output_dir / "cgr_solver.py").write_text(
        _render_generated_python_wrapper(spec, generated_at), encoding="utf-8"
    )
    examples_dir = output_dir / "examples"
    examples_dir.mkdir(parents=True, exist_ok=True)
    (examples_dir / "solve.rs").write_text(
        _render_generated_rust_example(spec, generated_at), encoding="utf-8"
    )
    (examples_dir / "solve.py").write_text(
        _render_generated_python_example(spec, output_dir.name, generated_at), encoding="utf-8"
    )

    bin_dir = src_dir / "bin"
    stale_json_solver = bin_dir / "cgr_solve_json.rs"
    stale_json_solver.unlink(missing_ok=True)
    if bin_dir.exists() and not any(bin_dir.iterdir()):
        bin_dir.rmdir()
    stale_main_rs = src_dir / "main.rs"
    stale_main_rs.unlink(missing_ok=True)
    if output_dir.exists():
        pycache_dir = output_dir / "__pycache__"
        if pycache_dir.exists():
            shutil.rmtree(pycache_dir)

    return GeneratedRustProject(spec=spec, output_dir=output_dir)
