from __future__ import annotations

import html
import math

from .config import (
    CLARABEL_VERSION,
    GENERATED_PYTHON_DEPENDENCIES,
    GENERATED_REQUIRES_PYTHON,
    GENERATOR_DISPLAY_NAME,
    GENERATOR_VERSION,
    MATURIN_VERSION,
    PYO3_VERSION,
    TEMPLATES_DIR,
)
from .names import _python_distribution_name, _rust_ident
from .specs import (
    ConeDimsSpec,
    CsrMatrixSpec,
    DualVariableSpec,
    MatrixPatternSpec,
    ParameterSpec,
    ProblemSpec,
    VariableSpec,
)


def _toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _toml_string_list(values: list[str], indent: str = "    ") -> str:
    return "\n".join(f"{indent}{_toml_string(value)}," for value in values)


def _load_template(name: str) -> str:
    return (TEMPLATES_DIR / name).read_text(encoding="utf-8")


def _fill_template(template: str, **values: str) -> str:
    for key, value in values.items():
        template = template.replace(f"__{key}__", value)
    return template


def _comment_block(prefix: str, lines: list[str]) -> str:
    return "\n".join(f"{prefix} {line}" if line else prefix.rstrip() for line in lines)


def _generated_header_lines(artifact: str, generated_at: str, module_name: str | None = None) -> list[str]:
    lines = [
        f"Generated by {GENERATOR_DISPLAY_NAME} v{GENERATOR_VERSION}",
        f"Generated at: {generated_at}",
        f"Artifact: {artifact}",
    ]
    if module_name is not None:
        lines.insert(3, f"Problem module: {module_name}")
    return lines


def _generated_header(prefix: str, artifact: str, generated_at: str, module_name: str | None = None) -> str:
    lines = _generated_header_lines(artifact, generated_at, module_name=module_name)
    if not prefix:
        return "\n".join(lines)
    return _comment_block(prefix, lines)


def _rust_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _rustdoc_text(value: str) -> str:
    return value.replace("\n", " ").replace("\r", " ")


def _shape_text(shape: tuple[int, ...]) -> str:
    if not shape:
        return "scalar"
    return " x ".join(str(dim) for dim in shape)


def _rustdoc_block(indent: str, lines: list[str]) -> str:
    return "\n".join(f"{indent}/// {_rustdoc_text(line)}" if line else f"{indent}///" for line in lines)


def _rust_usize_slice(values: list[int] | tuple[int, ...]) -> str:
    return "&[" + ", ".join(f"{value}usize" for value in values) + "]"


def _rust_vec(values: list[object], render_value, indent: str) -> str:
    if not values:
        return "vec![]"
    entries = "\n".join(f"{indent}    {render_value(value)}," for value in values)
    return f"vec![\n{entries}\n{indent}]"


def _rust_usize_vec(values: list[int], indent: str = "") -> str:
    return _rust_vec(values, lambda value: f"{value}usize", indent)


def _rust_f64(value: float) -> str:
    if math.isnan(value):
        raise ValueError("NaN coefficients are not supported")
    if math.isinf(value):
        return "f64::INFINITY" if value > 0 else "f64::NEG_INFINITY"
    if value == 0.0:
        return "0.0"
    return repr(float(value))


def _rust_f64_vec(values: list[float], indent: str = "") -> str:
    return _rust_vec(values, _rust_f64, indent)


def _render_csr(name: str, spec: CsrMatrixSpec) -> str:
    field_indent = "            "
    return f"""        let {name} = CsrMatrix {{
            rows: {spec.rows}usize,
            cols: {spec.cols}usize,
            indptr: {_rust_usize_vec(spec.indptr, field_indent)},
            indices: {_rust_usize_vec(spec.indices, field_indent)},
            data: {_rust_f64_vec(spec.data, field_indent)},
        }};"""


def _render_pattern(name: str, spec: MatrixPatternSpec) -> str:
    field_indent = "            "
    return f"""        let {name} = MatrixPattern {{
            rows: {spec.rows}usize,
            cols: {spec.cols}usize,
            indices: {_rust_usize_vec(spec.indices, field_indent)},
            indptr: {_rust_usize_vec(spec.indptr, field_indent)},
        }};"""


def _indent_rust_block(block: str, indent: str) -> str:
    return "\n".join(f"{indent}{line}" if line else line for line in block.splitlines())


def _render_parameter_info(parameter: ParameterSpec, field_indent: str = "    ") -> str:
    return f"""ParameterInfo {{
{field_indent}name: {_rust_string(parameter.name)},
{field_indent}shape: {_rust_usize_slice(parameter.shape)},
{field_indent}size: {parameter.size}usize,
{field_indent}offset: {parameter.offset}usize,
}}"""


def _render_variable_info(variable: VariableSpec, field_indent: str = "    ") -> str:
    return f"""VariableInfo {{
{field_indent}name: {_rust_string(variable.name)},
{field_indent}shape: {_rust_usize_slice(variable.shape)},
{field_indent}size: {variable.size}usize,
{field_indent}offset: {variable.offset}usize,
}}"""


def _render_dual_variable_info(dual_variable: DualVariableSpec, field_indent: str = "    ") -> str:
    return f"""DualVariableInfo {{
{field_indent}name: {_rust_string(dual_variable.name)},
{field_indent}shape: {_rust_usize_slice(dual_variable.shape)},
{field_indent}size: {dual_variable.size}usize,
{field_indent}offset: {dual_variable.offset}usize,
}}"""


def _render_cone_dims(spec: ConeDimsSpec) -> str:
    field_indent = "                "
    return f"""ConeDims {{
                zero: {spec.zero}usize,
                nonneg: {spec.nonneg}usize,
                exp: {spec.exp}usize,
                soc: {_rust_usize_vec(spec.soc, field_indent)},
                psd: {_rust_usize_vec(spec.psd, field_indent)},
                p3d: {_rust_f64_vec(spec.p3d, field_indent)},
            }}"""


def _render_rust_static_array(name: str, item_type: str, items: list[str]) -> str:
    if not items:
        return f"static {name}: [{item_type}; 0] = [];"
    if len(items) == 1:
        return f"static {name}: [{item_type}; 1] = [{items[0]}];"

    rendered_items = ",\n".join(_indent_rust_block(item, "    ") for item in items)
    return f"static {name}: [{item_type}; {len(items)}] = [\n{rendered_items},\n];"


def _render_generated_lib(spec: ProblemSpec, generated_at: str) -> str:
    parameters_static = _render_rust_static_array(
        "PARAMETERS",
        "ParameterInfo",
        [_render_parameter_info(parameter) for parameter in spec.parameters]
    )
    variables_static = _render_rust_static_array(
        "VARIABLES",
        "VariableInfo",
        [_render_variable_info(variable) for variable in spec.variables]
    )
    dual_variables_static = _render_rust_static_array(
        "DUAL_VARIABLES",
        "DualVariableInfo",
        [_render_dual_variable_info(dual_variable) for dual_variable in spec.dual_variables]
    )
    param_setters = []
    for parameter in spec.parameters:
        ident = _rust_ident(parameter.name)
        param_setters.append(
            f"""{_rustdoc_block("    ", [
                f"Replaces parameter `{parameter.name}`.",
                "",
                f"Shape: {_shape_text(parameter.shape)}. Flattened size: {parameter.size}. Offset: {parameter.offset}.",
                f"`value` must contain exactly {parameter.size} entries in CVXPY's flattened order.",
            ])}
    pub fn set_{ident}(&mut self, value: &[f64]) -> Result<(), RuntimeError> {{
        self.set_parameter({_rust_string(parameter.name)}, value)
    }}

{_rustdoc_block("    ", [
                f"Updates one scalar entry of parameter `{parameter.name}`.",
                "",
                f"`index` is zero-based within the flattened {parameter.size}-entry parameter block at offset {parameter.offset}.",
            ])}
    pub fn update_{ident}(&mut self, index: usize, value: f64) -> Result<(), RuntimeError> {{
        self.update_parameter_entry({_rust_string(parameter.name)}, index, value)
    }}
"""
        )

    variable_getters = []
    for variable in spec.variables:
        ident = _rust_ident(variable.name)
        variable_getters.append(
            f"""{_rustdoc_block("    ", [
                f"Extracts primal variable `{variable.name}` from `SolveResult.x`.",
                "",
                f"Shape: {_shape_text(variable.shape)}. Flattened size: {variable.size}. Offset: {variable.offset}.",
            ])}
    pub fn extract_{ident}(&self, solution: &[f64]) -> Result<Vec<f64>, RuntimeError> {{
        self.extract_variable({_rust_string(variable.name)}, solution)
    }}
"""
        )

    dual_variable_getters = []
    for dual_variable in spec.dual_variables:
        ident = _rust_ident(dual_variable.name)
        dual_variable_getters.append(
            f"""{_rustdoc_block("    ", [
                f"Extracts canonical dual block `{dual_variable.name}` from `SolveResult.z`.",
                "",
                f"Shape: {_shape_text(dual_variable.shape)}. Flattened size: {dual_variable.size}. Offset: {dual_variable.offset}.",
            ])}
    pub fn extract_{ident}(&self, dual_solution: &[f64]) -> Result<Vec<f64>, RuntimeError> {{
        self.extract_dual_variable({_rust_string(dual_variable.name)}, dual_solution)
    }}
"""
        )

    cone_push_lines = []
    if spec.cone_dims.zero > 0:
        cone_push_lines.append(
            "        cones.push(SupportedConeT::<f64>::ZeroConeT(canonical.cones.zero));"
        )
    if spec.cone_dims.nonneg > 0:
        cone_push_lines.append(
            "        cones.push(SupportedConeT::<f64>::NonnegativeConeT(\n            canonical.cones.nonneg,\n        ));"
        )
    if spec.cone_dims.soc:
        cone_push_lines.append(
            "        for dim in &canonical.cones.soc {\n            cones.push(SupportedConeT::<f64>::SecondOrderConeT(*dim));\n        }"
        )
    if spec.cone_dims.psd:
        cone_push_lines.append(
            "        for dim in &canonical.cones.psd {\n            cones.push(SupportedConeT::<f64>::PSDTriangleConeT(*dim));\n        }"
        )
    if spec.cone_dims.exp > 0:
        cone_push_lines.append(
            "        for _ in 0..canonical.cones.exp {\n            cones.push(SupportedConeT::<f64>::ExponentialConeT());\n        }"
        )
    if spec.cone_dims.p3d:
        cone_push_lines.append(
            "        for alpha in &canonical.cones.p3d {\n            cones.push(SupportedConeT::<f64>::PowerConeT(*alpha));\n        }"
        )
    cone_push_code = "\n".join(cone_push_lines)
    canonical_method = _fill_template(
        _load_template("clarabel_canonical_method.rs.tmpl"),
        P_REDUCED=_render_csr("p_reduced", spec.p_map.reduced),
        P_PATTERN=_render_pattern("p_pattern", spec.p_map.pattern),
        A_REDUCED=_render_csr("a_reduced", spec.a_map.reduced),
        A_PATTERN=_render_pattern("a_pattern", spec.a_map.pattern),
        Q_REDUCED=_render_csr("c_reduced", spec.q_map.reduced),
        Q_OUTPUT_LEN=str(spec.q_map.output_len),
        CONE_DIMS=_render_cone_dims(spec.cone_dims),
    )
    solve_method = _fill_template(
        _load_template("clarabel_solve_method.rs.tmpl"),
        CONE_PUSH_CODE=cone_push_code,
    )
    python_methods = _fill_template(
        _load_template("pyo3_module.rs.tmpl"),
        LIB_NAME=spec.module_name.replace("-", "_"),
        PARAMETER_VEC_LEN=str(spec.parameter_vec_len),
        PARAMETER_VEC_LEN_MINUS_ONE=str(spec.parameter_vec_len - 1),
    )

    rendered = _fill_template(
        _load_template("cgr_lib.rs.tmpl"),
        RUNTIME_RS=_fill_template(
            _load_template("runtime.rs.tmpl"),
            HEADER=_generated_header(
                "//",
                "Rust solver backend with canonicalization maps, Clarabel integration, and Python bindings",
                generated_at,
                module_name=spec.module_name,
            ),
        ),
        PARAMETERS_STATIC=parameters_static,
        VARIABLES_STATIC=variables_static,
        DUAL_VARIABLES_STATIC=dual_variables_static,
        PARAMETER_VEC_LEN_MINUS_ONE=str(spec.parameter_vec_len - 1),
        CANONICAL_METHOD=canonical_method,
        SOLVE_METHOD=solve_method,
        PYTHON_METHODS=python_methods,
        PARAM_SETTERS="".join(param_setters),
        VARIABLE_GETTERS="".join(variable_getters),
        DUAL_VARIABLE_GETTERS="".join(dual_variable_getters),
    )
    return rendered.rstrip() + "\n"


def _render_generated_pyproject(spec: ProblemSpec, package_name: str, generated_at: str) -> str:
    return _fill_template(
        _load_template("pyproject.toml.tmpl"),
        HEADER=_generated_header(
            "#",
            "Python build manifest for compiling the generated PyO3 extension with maturin",
            generated_at,
            module_name=spec.module_name,
        ),
        PROJECT_NAME=_python_distribution_name(package_name),
        PACKAGE_NAME=package_name,
        MODULE_NAME=spec.module_name,
        LIB_NAME=spec.module_name.replace("-", "_"),
        REQUIRES_PYTHON=GENERATED_REQUIRES_PYTHON,
        MATURIN_VERSION=MATURIN_VERSION,
        PYTHON_DEPENDENCIES=_toml_string_list(GENERATED_PYTHON_DEPENDENCIES),
    )


def _render_generated_init(spec: ProblemSpec, generated_at: str) -> str:
    return _generated_header(
        "#",
        "Generated Python solver module init file",
        generated_at,
        module_name=spec.module_name,
    ) + "\n"


def _render_generated_license(spec: ProblemSpec, generated_at: str) -> str:
    return _fill_template(
        _load_template("LICENSE.tmpl"),
        HEADER=_generated_header(
            "",
            "License for the generated solver support code",
            generated_at,
            module_name=spec.module_name,
        ),
    )


def _render_generated_cargo(spec: ProblemSpec, generated_at: str) -> str:
    if spec.cone_dims.psd:
        dependencies = """[target.'cfg(target_os = "macos")'.dependencies]
clarabel = { version = "__CLARABEL_VERSION__", features = ["sdp-accelerate", "faer-sparse"] }

[target.'cfg(not(target_os = "macos"))'.dependencies]
clarabel = { version = "__CLARABEL_VERSION__", features = ["sdp-openblas", "faer-sparse"] }"""
    else:
        dependencies = 'clarabel = "__CLARABEL_VERSION__"'
    return _fill_template(
        _load_template("Cargo.toml.tmpl"),
        HEADER=_generated_header(
            "#",
            "Cargo manifest for the generated solver crate",
            generated_at,
            module_name=spec.module_name,
        ),
        CRATE_NAME=spec.module_name,
        LIB_NAME=spec.module_name.replace("-", "_"),
        DEPENDENCIES=dependencies.replace("__CLARABEL_VERSION__", CLARABEL_VERSION),
        PYO3_VERSION=PYO3_VERSION,
    )


def _render_generated_readme(
    spec: ProblemSpec, package_name: str, output_dir_name: str, generated_at: str
) -> str:
    def code(value: str) -> str:
        return html.escape(value, quote=False)

    def attr(value: str) -> str:
        return html.escape(value, quote=True)

    def dimension(shape: tuple[int, ...], size: int) -> str:
        if not shape:
            return "scalar"
        shape_text = " x ".join(str(item) for item in shape)
        return f"{shape_text} ({size})" if size != math.prod(shape) else shape_text

    parameter_rows = "\n".join(
        "          <tr>"
        f"<td><code>{code(parameter.name)}</code></td>"
        f"<td>{code(dimension(parameter.shape, parameter.size))}</td>"
        f"<td>{parameter.size}</td>"
        f"<td>{parameter.offset}</td>"
        "</tr>"
        for parameter in spec.parameters
    ) or '          <tr><td colspan="4">No parameters</td></tr>'
    variable_rows = "\n".join(
        "          <tr>"
        f"<td><code>{code(variable.name)}</code></td>"
        f"<td>{code(dimension(variable.shape, variable.size))}</td>"
        f"<td>{variable.size}</td>"
        f"<td>{variable.offset}</td>"
        "</tr>"
        for variable in spec.variables
    ) or '          <tr><td colspan="4">No variables</td></tr>'
    dual_variable_rows = "\n".join(
        "          <tr>"
        f"<td><code>{code(dual_variable.name)}</code></td>"
        f"<td>{code(dimension(dual_variable.shape, dual_variable.size))}</td>"
        f"<td>{dual_variable.size}</td>"
        f"<td>{dual_variable.offset}</td>"
        "</tr>"
        for dual_variable in spec.dual_variables
    ) or '          <tr><td colspan="4">No canonical dual blocks</td></tr>'
    setter_lines = "\n".join(
        f"problem.set_{_rust_ident(parameter.name)}(&vec![0.0; {parameter.size}])?;"
        for parameter in spec.parameters
    )
    value_lines = ""
    if spec.variables:
        variable = spec.variables[0]
        ident = _rust_ident(variable.name)
        value_lines = (
            f"\nlet {ident} = problem.extract_{ident}(&solution.x)?;\n"
            f'println!("value = {{:?}}", {ident});'
        )
    rust_usage = _fill_template(
        """use __MODULE_NAME__::CGRProblem;

let mut problem = CGRProblem::new();
__SETTER_LINES__

let solution = problem.solve()?;
println!("status = {}", solution.status);
println!("objective = {}", solution.obj_val);__VALUE_LINES__
""",
        MODULE_NAME=spec.module_name,
        SETTER_LINES=setter_lines,
        VALUE_LINES=value_lines,
    ).strip()
    python_usage = _fill_template(
        """# Assume `problem` and the listed CVXPY parameters/variables are already defined.
import numpy as np
from __PACKAGE_NAME__.cgr_solver import cgr_solve

problem.register_solve("CGR", cgr_solve)
__PARAM_ASSIGNMENTS__

problem.solve(
    method="CGR",
    updated_params=[
        __UPDATED_PARAMS__
    ]
)
print(problem.status)
""",
        PACKAGE_NAME=package_name,
        PARAM_ASSIGNMENTS="\n".join(
            f"{parameter.name}.value = "
            + (
                "0.0"
                if parameter.size == 1
                else f"np.zeros({repr(tuple(parameter.shape)) if len(parameter.shape) != 1 else f'({parameter.shape[0]},)'})"
            )
            for parameter in spec.parameters
        ),
        UPDATED_PARAMS=",\n        ".join(repr(parameter.name) for parameter in spec.parameters),
    ).strip()
    generated_setters = "\n".join(
        f"    pub fn set_{_rust_ident(parameter.name)}(&mut self, value: &[f64]) -> Result<(), RuntimeError>;\n"
        f"    pub fn update_{_rust_ident(parameter.name)}(&mut self, index: usize, value: f64) -> Result<(), RuntimeError>;"
        for parameter in spec.parameters
    ) or "    // No generated parameter setters: this problem has no parameters."
    generated_extractors = "\n".join(
        f"    pub fn extract_{_rust_ident(variable.name)}(&self, solution: &[f64]) -> Result<Vec<f64>, RuntimeError>;"
        for variable in spec.variables
    ) or "    // No generated variable extractors."
    generated_dual_extractors = "\n".join(
        f"    pub fn extract_{_rust_ident(dual_variable.name)}(&self, dual_solution: &[f64]) -> Result<Vec<f64>, RuntimeError>;"
        for dual_variable in spec.dual_variables
    ) or "    // No generated dual block extractors."
    rust_api_snippet = _fill_template(
        """pub struct CGRProblem { ... }

impl CGRProblem {
    // Construct a problem object with zero-filled parameters and quiet Clarabel settings.
    pub fn new() -> Self;

    // Static metadata for generated parameter, primal variable, and canonical dual layouts.
    pub fn parameter_info(&self) -> &'static [ParameterInfo];
    pub fn variable_info(&self) -> &'static [VariableInfo];
    pub fn dual_variable_info(&self) -> &'static [DualVariableInfo];

    // Flattened parameter vector in CVXPY canonical order, including the trailing constant slot.
    pub fn parameter_vector(&self) -> Vec<f64>;

    // Clarabel settings accessors and common convenience setters.
    pub fn solver_settings(&self) -> &clarabel::solver::DefaultSettings<f64>;
    pub fn solver_settings_mut(&mut self) -> &mut clarabel::solver::DefaultSettings<f64>;
    pub fn set_solver_default_settings(&mut self);
    pub fn set_solver_verbose(&mut self, verbose: bool);
    pub fn set_solver_max_iter(&mut self, max_iter: u32);
    pub fn set_solver_time_limit(&mut self, time_limit: f64);
    pub fn set_solver_tol_gap_abs(&mut self, tol_gap_abs: f64);
    pub fn set_solver_tol_gap_rel(&mut self, tol_gap_rel: f64);
    pub fn set_solver_tol_feas(&mut self, tol_feas: f64);

    // Generic and generated parameter setters. Entry updates use zero-based flattened indices.
    pub fn set_parameter(&mut self, name: &str, value: &[f64]) -> Result<(), RuntimeError>;
    pub fn update_parameter_entry(&mut self, name: &str, index: usize, value: f64) -> Result<(), RuntimeError>;
__GENERATED_SETTERS__

    // Build the current canonical cone program data, or solve it with Clarabel.
    pub fn canonical_cone_prob(&self) -> Result<CanonicalConeQp, RuntimeError>;
    pub fn solve(&self) -> Result<SolveResult, RuntimeError>;

    // Extract primal variables from SolveResult.x.
    pub fn extract_variable(&self, name: &str, solution: &[f64]) -> Result<Vec<f64>, RuntimeError>;
__GENERATED_EXTRACTORS__

    // Extract canonical dual blocks from SolveResult.z. These are not always one-to-one
    // with original CVXPY constraints if canonicalization split a constraint.
    pub fn extract_dual_variable(&self, name: &str, dual_solution: &[f64]) -> Result<Vec<f64>, RuntimeError>;
__GENERATED_DUAL_EXTRACTORS__
}

pub struct SolveResult {
    pub x: Vec<f64>,      // primal solution vector
    pub z: Vec<f64>,      // canonical dual solution vector
    pub s: Vec<f64>,      // slack vector
    pub status: String,
    pub obj_val: f64,
    pub iterations: u32,
    pub r_prim: f64,
    pub r_dual: f64,
}""",
        GENERATED_SETTERS=generated_setters,
        GENERATED_EXTRACTORS=generated_extractors,
        GENERATED_DUAL_EXTRACTORS=generated_dual_extractors,
    )
    return _fill_template(
        _load_template("cgr_README.html.tmpl"),
        MODULE_NAME=attr(spec.module_name),
        MODULE_NAME_TEXT=code(spec.module_name),
        PACKAGE_NAME=attr(package_name),
        PACKAGE_NAME_TEXT=code(package_name),
        OUTPUT_DIR_NAME_TEXT=code(output_dir_name),
        GENERATED_AT=code(generated_at),
        GENERATOR_VERSION=code(GENERATOR_VERSION),
        PARAMETER_ROWS=parameter_rows,
        VARIABLE_ROWS=variable_rows,
        DUAL_VARIABLE_ROWS=dual_variable_rows,
        RUST_API_SNIPPET=code(rust_api_snippet),
        RUST_USAGE=code(rust_usage),
        PYTHON_USAGE=code(python_usage),
    )


def _render_generated_python_wrapper(spec: ProblemSpec, generated_at: str) -> str:
    parameter_entries = ",\n    ".join(
        repr(
            dict(
                name=parameter.name,
                shape=list(parameter.shape),
                size=parameter.size,
                offset=parameter.offset,
                pack=parameter.pack,
            )
        )
        for parameter in spec.parameters
    )
    return _fill_template(
        _load_template("cgr_solver.py.tmpl"),
        HEADER=_generated_header(
            "#",
            "CVXPY solve-method wrapper for the generated solver",
            generated_at,
            module_name=spec.module_name,
        ),
        PARAMETER_ENTRIES=parameter_entries,
        PARAMETER_VEC_LEN=str(spec.parameter_vec_len),
        LIB_NAME=spec.module_name.replace("-", "_"),
        SOLVER_METHOD_NAME=f"{spec.module_name}_cgr",
    )


def _render_generated_rust_example(spec: ProblemSpec, generated_at: str) -> str:
    param_setup = []
    for parameter in spec.parameters:
        ident = _rust_ident(parameter.name)
        param_setup.append(
            f"""    problem.set_{ident}(&vec![0.0; {parameter.size}])?;"""
        )

    variable_readback = ""
    if spec.variables:
        first_variable = spec.variables[0]
        first_ident = _rust_ident(first_variable.name)
        variable_readback = f"""
    let {first_ident} = problem.extract_{first_ident}(&solution.x)?;
    println!("{first_ident} = {{:?}}", {first_ident});"""

    solve_call = "problem.solve()?"

    return _fill_template(
        _load_template("cgr_solve.rs.tmpl"),
        HEADER=_generated_header(
            "//",
            "Rust example executable",
            generated_at,
            module_name=spec.module_name,
        ),
        MODULE_NAME=spec.module_name,
        PARAM_SETUP=chr(10).join(param_setup),
        SOLVE_CALL=solve_call,
        VARIABLE_READBACK=variable_readback,
    )
